### ISSUE TITLE
Make sure URL is correct

### ISSUE THREAD

**Issue by ANewmy** [IonicaBizau/jQuery-cross-domain-requests#11]
Seems like every URL I try results in the "There was a problem with the page. Be sure that your URL is correct" message. Any idea why I can't get passed this issue?

**Comment by ANewmy** [comment]
After looking around, seems like a recent YQL API update has been causing issues with other repos.

**Comment by IonicaBizau** [comment]
Ah, good point! Such changes do break the library.
