### ISSUE TITLE
Issues with index2.html and index3.html live demos

### ISSUE THREAD

**Issue by kkerley** [IonicaBizau/jQuery-cross-domain-requests#6]
I've tried both versions and each throws its own set of Javascript errors in the console. This is the URL I'm using to attempt pulling in content:
http://themetalcorebreakdown.com/reviews/stick-to-your-guns-disobedience-review/

**Index2.html**
- ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index2.html:1 Refused to execute script from 'https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/js/jquery.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
- ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index2.html:1 Refused to execute script from 'https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/js/jquery.xdomainajax.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
- ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index2.html:3 Uncaught ReferenceError: $ is not defined

**Index3.html**
- htmlpreview.min.js:1 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://raw.githubusercontent.com/IonicaBizau/jQuery-cross-domain-requests/master/style.css".(anonymous function) @ htmlpreview.min.js:1
- ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index3.html:1 Refused to execute script from 'https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/js/jquery.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
- ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index3.html:1 Refused to execute script from 'https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/js/jquery.xdomainajax.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
- ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index3.html:1 Refused to execute script from 'https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/js/clientJs.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
- ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index3.html:1 Uncaught ReferenceError: getHTMLContent is not definedonclick @ ?https://raw.github.com/IonicaBizau/jQuery-cross-domain-requests/master/index3.html:1

**Comment by IonicaBizau** [comment]
The live demos are broken because of the `htmlpreview` thingy...

You can preview them using rawgit:

> https://rawgit.com/IonicaBizau/jQuery-cross-domain-requests/master/index3.html

If you have some free time, I'd be happy if you fixed these in the docs. 😁

**Comment by kkerley** [comment]
Ahhh understood! Thanks for the working link!
